[package]
name = "entry"
version = "0.1.0"
authors = ["JAESEUNG LEE <tkxkd0159@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant = { path = "../restaurant" }
chrono = "0.4"